name: Land
main: cn.smallaswater.land.LandMainClass
version: 1.7.5
api: 1.0.9
load: POSTWORLD
softdepend:
  - AutoUpData

permissions:
  Land.land:
    description: "领地权限"
    default: true
  Land.admin:
    description: "领地管理员"
    default: op